import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';

/**
 * Shared UBoss ESLint (flat) base.
 *
 * Type-aware linting (`recommendedTypeChecked`) is deliberately NOT enabled at Prompt 1:
 * it needs a resolved project graph in every workspace and would slow the bootstrap loop.
 * See docs/ARCHITECTURE_DECISIONS.md (ADR-008) for the trigger to turn it on.
 */
export const ignores = [
  '**/node_modules/**',
  '**/dist/**',
  '**/dist-test/**',
  '**/dist-scripts/**',
  // Generated Prisma client — regenerated by `prisma generate`, never edited by hand.
  '**/src/generated/**',
  '**/.next/**',
  '**/coverage/**',
  '**/*.tsbuildinfo',
  // Client-supplied static UI reference prototype — kept verbatim, never linted or edited.
  'index.html',
];

/** Rules applied to every TypeScript file in the repository. */
export const ubossRules = {
  // Unused code is a review smell; allow the conventional leading-underscore escape hatch.
  '@typescript-eslint/no-unused-vars': [
    'error',
    { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
  ],
  // `any` erodes the tenant/permission types this product depends on.
  '@typescript-eslint/no-explicit-any': 'error',
  // Structured logging only. Nest uses Logger; the web app must not ship console noise.
  'no-console': ['error', { allow: ['warn', 'error'] }],
  eqeqeq: ['error', 'always', { null: 'ignore' }],
  'no-var': 'error',
  'prefer-const': 'error',
  'no-throw-literal': 'error',
};

/**
 * Build the flat config array for a workspace.
 * @param {{ extraIgnores?: string[] }} [options]
 */
export function ubossConfig(options = {}) {
  return tseslint.config(
    { ignores: [...ignores, ...(options.extraIgnores ?? [])] },
    {
      files: ['**/*.{js,mjs,cjs,ts,mts,cts,tsx}'],
      extends: [js.configs.recommended, ...tseslint.configs.recommended],
      rules: ubossRules,
    },
    {
      // React surfaces: hook correctness is enforced, since a mis-ordered hook silently breaks
      // the loading / empty / error / permission-denied states every screen is required to have.
      files: ['**/*.tsx'],
      plugins: { 'react-hooks': reactHooks },
      rules: {
        'react-hooks/rules-of-hooks': 'error',
        'react-hooks/exhaustive-deps': 'warn',
      },
    },
    {
      // Config and operational scripts run in Node, and their console output is their interface
      // (a seed that reports nothing is worse than one that does).
      files: [
        '**/*.config.{js,mjs,cjs,ts,mts}',
        '**/*.setup.{ts,tsx}',
        '**/prisma/seed.ts',
        '**/scripts/**/*.{ts,mts,js,mjs}',
      ],
      rules: { 'no-console': 'off' },
    },
    {
      // Tests may use non-null assertions to keep assertions readable.
      files: ['**/*.{test,spec}.{ts,tsx}', '**/*.e2e-spec.ts'],
      rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
    },
  );
}

export default ubossConfig;
